spring:
  application:
    name: devtanush-product-enquiry-service
server:
  port: ${port:8700}

devtanush-product-stock-service:
  ribbon:
    listOfServers: http://localhost:8800, http://localhost:8801